# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=False, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(primary_key=True)),
                ('image', models.BinaryField()),
                ('label', models.IntegerField()),
            ],
        ),
    ]
