# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traindata',
            old_name='cnt',
            new_name='idx',
        ),
    ]
